name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cd kodeline && cargo build --release --verbose
    - name: Run tests
      run: cd kodeline && cargo test --verbose
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
       tag_name: ${{ github.ref }}
       release_name: Release ${{ github.ref }}
       body: |
          Changes in this Release
            - First Change
            - Second Change
       draft: false
       prerelease: false
